site_name: FAQ Chatbot API
site_description: Documentation for the FastAPI-based FAQ chatbot
repo_url: https://github.com/supremekhadka/faq_chatbot_fastapi

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - tables

nav:
  - Home: index.md
